{"uuid": "7cc26d7b-1bac-464e-abc2-0f18effb7be2", "children": ["99dbe3d7-a56b-4db6-ae34-eaac7fb04c77"], "befores": [{"name": "init_create_project", "status": "broken", "statusDetails": {"message": "requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /api/v3/projects (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000023FCFE156A0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))\n", "trace": "  File \"C:\\Users\\nirel\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\nirel\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\_pytest\\fixtures.py\", line 1126, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\nirel\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\_pytest\\fixtures.py\", line 932, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"C:\\Programming\\Automation\\Project\\apiTesting\\tests\\test_4.py\", line 21, in init_create_project\n    response = ProjectApi().post_new_project(self.new_project_name)\n  File \"C:\\Programming\\Automation\\Project\\apiTesting\\api\\project_api.py\", line 33, in post_new_project\n    response = super().post(path=\"/api/v3/projects\", payload=payload)\n  File \"C:\\Programming\\Automation\\Project\\apiTesting\\api\\rest_client.py\", line 26, in post\n    response = requests.request(\"POST\", url=self.__base_url + path, headers=self.__headers, data=payload)\n  File \"C:\\Users\\nirel\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\api.py\", line 61, in request\n    return session.request(method=method, url=url, **kwargs)\n  File \"C:\\Users\\nirel\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py\", line 542, in request\n    resp = self.send(prep, **send_kwargs)\n  File \"C:\\Users\\nirel\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\sessions.py\", line 655, in send\n    r = adapter.send(request, **kwargs)\n  File \"C:\\Users\\nirel\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\requests\\adapters.py\", line 516, in send\n    raise ConnectionError(e, request=request)\n"}, "start": 1625586290521, "stop": 1625586294527}], "start": 1625586290521, "stop": 1625586311614}