{"name": "test_second", "status": "failed", "statusDetails": {"message": "AssertionError: Houston we've got a problem\nassert 4 == 5", "trace": "self = <test_1.TestOne object at 0x00000168B33B7F70>\ninit_web_driver = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"94cf2a70562c448e3ea3dde4a2732f16\")>\n\n    @pytest.mark.sanity\n    def test_second(self, init_web_driver):\n        init_web_driver.get(\"https://www.gmail.com\")\n>       assert 2 + 2 == 5, \"Houston we've got a problem\"\nE       AssertionError: Houston we've got a problem\nE       assert 4 == 5\n\ntest_1.py:23: AssertionError"}, "start": 1623671004221, "stop": 1623671008236, "uuid": "23ab129f-437d-444c-8c47-f4ebf15b3d7b", "historyId": "18eab4814b7571795a9a00922c03716f", "testCaseId": "a67ff91e5296a75f95cbfd9f194a279c", "fullName": "test_1.TestOne#test_second", "labels": [{"name": "tag", "value": "sanity"}, {"name": "tag", "value": "system"}, {"name": "suite", "value": "test_1"}, {"name": "subSuite", "value": "TestOne"}, {"name": "host", "value": "LAPTOP-KHP8ML6J"}, {"name": "thread", "value": "14612-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_1"}]}