{"name": "test_second", "status": "failed", "statusDetails": {"message": "AssertionError: Houston we've got a problem\nassert 4 == 5", "trace": "self = <test_1.TestOne object at 0x000001F717AED280>\ninit_web_driver = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"52ac6f28187d9c1813d09650e7a3b65d\")>\n\n    @pytest.mark.sanity\n    def test_second(self, init_web_driver):\n        init_web_driver.get(\"https://www.gmail.com\")\n>       assert 2 + 2 == 5, \"Houston we've got a problem\"\nE       AssertionError: Houston we've got a problem\nE       assert 4 == 5\n\ntest_1.py:23: AssertionError"}, "start": 1624295336136, "stop": 1624295341028, "uuid": "33aca73d-be6e-49e6-82f7-2a0a2f13310b", "historyId": "18eab4814b7571795a9a00922c03716f", "testCaseId": "a67ff91e5296a75f95cbfd9f194a279c", "fullName": "test_1.TestOne#test_second", "labels": [{"name": "tag", "value": "sanity"}, {"name": "tag", "value": "system"}, {"name": "suite", "value": "test_1"}, {"name": "subSuite", "value": "TestOne"}, {"name": "host", "value": "LAPTOP-KHP8ML6J"}, {"name": "thread", "value": "26488-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_1"}]}